version: '3.8'

services:
  app:
    build: .
    volumes:
      - static_data:/vol/web
      - ./restaurant_orders/:/usr/src/app
    command: "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - STATIC_DIR=/vol/web
      - REDIS_HOST=redis
      - DB_POSTGRES=1
      - DB_NAME=django
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=db
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"
    links:
      - redis
      - db
  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  redis:
    image: redis:latest

  celery_worker:
    build: .
    command: "celery.sh"
    volumes:
      - ./restaurant_orders/:/usr/src/app
    environment:
      - DEBUG=1
      - REDIS_HOST=redis
    depends_on:
      - redis
      - db

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: jdlugosz963@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: 1234
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   links:
  #     - db

volumes:
  static_data:
  pg_data:
  # pgadmin_data:
